# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import transaction_pb2 as transaction__pb2


class TransactionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.newTransaction = channel.unary_unary(
        '/Transaction/newTransaction',
        request_serializer=transaction__pb2.TransactionRequest.SerializeToString,
        response_deserializer=transaction__pb2.TransactionResponse.FromString,
        )


class TransactionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def newTransaction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TransactionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'newTransaction': grpc.unary_unary_rpc_method_handler(
          servicer.newTransaction,
          request_deserializer=transaction__pb2.TransactionRequest.FromString,
          response_serializer=transaction__pb2.TransactionResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Transaction', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
